[project]
name = "adk-deep-research"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "chromadb>=1.1.1",
    "fastmcp>=2.13.1",
    "google-adk>=0.3.0",
    "google-genai>=1.51.0",
]

[tool.uv.sources]
google-adk = { workspace = true }
