"""
Managed Researcher Agent - Wrapper for Official Gemini Deep Research

Role: Interfaces with the official 'deep-research-pro-preview' model via the Interactions API.
Input: A complex research topic.
Output: The full text report generated by the managed agent.

This acts as the "Big Brain" in the hybrid architecture, handling complex reasoning and
broad historical/general topics that require massive scale search.
"""
import asyncio
import os
import sys
from google import genai
from google.genai import types

class ManagedResearcherAgent:
    def __init__(self, api_key: str = None, model_name: str = "deep-research-pro-preview-12-2025"):
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
        if not self.api_key:
            # We don't raise error here, but warn. Orchestrator should check availability.
            sys.stderr.write("[ManagedResearcher] WARN: GEMINI_API_KEY not found.\n")
            
        self.model_name = model_name
        self.client = None
        if self.api_key:
            self.client = genai.Client(api_key=self.api_key)

    async def execute(self, topic: str, poll_interval: int = 10) -> str:
        """
        Executes a deep research task using the managed API.
        
        Args:
            topic: The research question or topic.
            poll_interval: Seconds to wait between status checks.
            
        Returns:
            The final report text, or an error message.
        """
        if not self.client:
            return "ERROR: Managed Deep Research unavailable (Missing API Key)."

        try:
            sys.stderr.write(f"[ManagedResearcher] Starting managed task: {topic[:50]}...\n")
            
            # Create interaction (Sync call wrapped)
            interaction = await asyncio.to_thread(
                self.client.interactions.create,
                input=topic,
                agent=self.model_name,
                background=True
            )
            
            sys.stderr.write(f"[ManagedResearcher] Task ID: {interaction.id}\n")
            
            # Polling Loop
            while True:
                await asyncio.sleep(poll_interval)
                
                # Get status
                current_interaction = await asyncio.to_thread(
                    self.client.interactions.get,
                    id=interaction.id
                )
                
                status = current_interaction.status
                sys.stderr.write(f"[ManagedResearcher] Status: {status}\n")
                
                if status == "completed":
                    if current_interaction.outputs:
                        return current_interaction.outputs[-1].text
                    return "ERROR: Task completed but returned no output."
                    
                elif status == "failed":
                    error_msg = f"Managed Research Failed: {current_interaction.error}"
                    sys.stderr.write(f"[ManagedResearcher] {error_msg}\n")
                    return f"ERROR: {error_msg}"
                
                # Continue polling if "running" or other states

        except Exception as e:
            return f"ERROR: Exception in Managed Researcher: {str(e)}"

# Singleton/Factory pattern for easy import
def get_managed_researcher():
    return ManagedResearcherAgent()
